version: "3"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:

services:
  strapi:
    image: strapi/strapi:3.6.8-alpine
    container_name: strapi
    restart: unless-stopped
    env_file: .env.example
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"

  mongo:
    image: mongo:4.2.16-rc0
    container_name: mongo
    restart: unless-stopped
    env_file: .env.example
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
